name: CD / Auto-Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write # required for provenance signing
jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0 # required for bump to work
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - run: npm run test -- --experimental-test-coverage --test-reporter=lcov --test-reporter-destination=lcov.info
      - uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm run bump
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm run bump
          git push --follow-tags
      - run: npm publish --provenance --access public
      - name: gh release create
        run: |
          VERSION="v$(jq -r .version package.json)"
          TARBALL=$(npm pack)
          gh release create "$VERSION" "$TARBALL" --title "$VERSION" --latest --generate-notes --verify-tag --discussion-category "General"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
